name: Run Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**' 
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'tsconfig.node-tests.json'
      - 'jest.config.js'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json' 
      - 'tsconfig.json'
      - 'tsconfig.node-tests.json'
      - 'jest.config.js'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run All Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npm run typecheck

    - name: Run all tests
      run: npm test -- --coverage --watchAll=false

    - name: Print Node and npm versions
      run: |
        node -v
        npm -v

    - name: Run terminal tests (Node test runner)
      env:
        TERM: xterm-256color
        COLORTERM: truecolor
      run: npm run test:terminal

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: false
