name: Run Tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**' 
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - 'jest.config.js'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'package-lock.json' 
      - 'tsconfig.json'
      - 'jest.config.js'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npm run typecheck

    - name: Run tests
      run: npm test -- --coverage --watchAll=false

    - name: Upload coverage reports to Codecov
      if: matrix.node-version == '20.x'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info
        fail_ci_if_error: false

  test-working-only:
    runs-on: ubuntu-latest
    name: Test Working Suite
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run working tests only (unit + integration)
      run: npm test -- tests/unit tests/integration --coverage --watchAll=false

    - name: Verify test results
      run: |
        echo "✅ Unit and Integration tests passed"
        echo "📊 Running test summary..."
        npm test -- tests/unit tests/integration --verbose --passWithNoTests=false